from macllm.tools.time import get_current_time
from macllm.tools.web_search import web_search, reset_search_counter
from macllm.tools.note import (
    search_notes,
    read_note,
    note_append,
    note_create,
    note_modify,
    note_move,
    note_delete,
    list_folder,
    view_folder_structure,
)
from macllm.tools.calendar import (
    cal_list_calendars,
    cal_get_events,
    cal_find_events,
    cal_add_event,
    cal_update_event,
    cal_find_free_time,
)
from macllm.tools.things import (
    things_list_areas,
    things_list_projects,
    things_list_tags,
    things_list_todos,
    things_search,
    things_get_item,
    things_show_item,
    things_create_todo,
    things_create_project,
    things_update_todo,
    things_update_project,
    things_complete_item,
    things_cancel_item,
)
from macllm.tools.shell import run_command
from macllm.tools.skills import read_skill
# Note: reset_search_counter is NOT in __all__ because it's a utility function,
# not a tool. Import it directly when needed.
__all__ = [
    "get_current_time",
    "web_search",
    "search_notes",
    "read_note",
    "note_append",
    "note_create",
    "note_modify",
    "note_move",
    "note_delete",
    "list_folder",
    "view_folder_structure",
    "cal_list_calendars",
    "cal_get_events",
    "cal_find_events",
    "cal_add_event",
    "cal_update_event",
    "cal_find_free_time",
    "things_list_areas",
    "things_list_projects",
    "things_list_tags",
    "things_list_todos",
    "things_search",
    "things_get_item",
    "things_show_item",
    "things_create_todo",
    "things_create_project",
    "things_update_todo",
    "things_update_project",
    "things_complete_item",
    "things_cancel_item",
    "run_command",
    "read_skill",
]
